### ISSUE TITLE
Also build error with Visual Studio 2015

### ISSUE THREAD

**Issue by SatoshiNakamotoBitcoins** [jairopaiva/BitcoinExprCracker#2]
See pic below for errors...
![VS2015](https://user-images.githubusercontent.com/45945164/69196388-a56ce600-0b2e-11ea-9813-e471925d2d69.PNG)

**Comment by jairopaiva** [comment]
You have to restore the packages before build it.

Enable package restore by choosing Tools > Options > NuGet Package Manager. Under Package Restore options, select Allow NuGet to download missing packages.

In Solution Explorer, right click the solution and select Restore NuGet Packages.

Here are the file with all packages that is needed in order to compile the project: BitcoinExprCracker/blob/master/BitcoinExprCracker/packages.config

**Comment by SatoshiNakamotoBitcoins** [comment]
@jairopaiva Thank you my friend...keep up the good work...

**Comment by SatoshiNakamotoBitcoins** [comment]
@jairopaiva Is your app able when I put a public key as a hex input (so uncompressed starting with 04 or compressed starting with 02 or 03) to retrieve the private key, and the TRYES...when yes...is it necessary to enter the prefix 02 or 03 for compressed (actually a hex string less than 256 bit) and with uncompressed prefix 04 (without the prefix the string is spot on the length of  256 bits but with prefix it goes BEYOUND the 256 bits space...)

Like to learn from you...

Cheers Satoshi

**Comment by jairopaiva** [comment]
Yes and no. The input needs to be an valid hex private key, because the app uses it to know the correct try number.  If you enter a public key, formatted to be 256 bit, the program will use it as a private key.
You're welcome, and any question or suggestion, please, contact me.

**Comment by SatoshiNakamotoBitcoins** [comment]
@jairopaiva Thank you for your answer...can you explain something more about the TRYES...is it a reference with the ASCII table...something like this??

https://www.ascii-code.com/

**Comment by SatoshiNakamotoBitcoins** [comment]
@jairopaiva I translated your .pdf explanation...

Generation of Expression and Pseudo Aleate
This step consists in the generation through a predefined algorithm of mathematical expressions based on a given public key according to the desired private key position.
For example:
Public Key: (65 bytes)
04CDDCE816EF153B8E8EADECE2A6489481B7332FD99A4718066C40B1B688F6A08828 241A5CC0A97E2C916C2EC610838325FB49403BB3ED352BB4574776FEC5E3B3, ie
X = CDDCE816EF153B8E8EADECE2A6489481B7332FD99A4718066C40B1B688F6A088
Y = 28241A5CC0A97E2C916C2EC610838325FB49403BB3ED352BB4574776FEC5E3B3
Private Key: (32 bytes)
375D75D0A1188016E9DE9395BFF6334BD3FDCEB5884766CE87454DB30612D936
Get private key value at position 0 (0x37):
After 513 attempts the following expression is generated:
 (Y [12] ^ Y [12]) * (Y [18] ^ Y [26]) + (Y [6] | Y [14])% (X [13] | X [31]), replacing the values ​​and calculating the result of the expression, we get 55 or 0x37 (correct private key value at position 0).
Now let's try to generate the expression that leads to the value of the private key at position 1:
After 270 attempts the following expression is generated:
(X [18]% Y [23]) | (~ Y [10] * X [0]), substituting values ​​and calculating the result of the expression results in 93 or 0x5D (correct private key value at position 1).
The algorithm has 3 input values: Public Key (X and Y), Private Key Position to be discovered (0-31), and Attempt (0-𝟐𝟔𝟒).
Using the above public key as an example (knowing the correct value of the private key) will result in: [513, 270, 151, 500, 546, 176, 305, 823, 369, 1310,
751, 792, 30, 61, 464, 3419, 1091, 84, 780, 52, 313, 112, 447, 52, 265, 10, 333, 775, 622, 2, 92, 2], each value refers to the attempt in which the expression was generated that resulted in the correct value of the private key in its respective position.

It refers to 3 input values:
-Public Key (X and Y)...so without prefix uncompressed...
-Private Key Position to be discovered (0-31)
- Attempt (0-𝟐𝟔𝟒)

Can you give some different example commands to run the app regarding those 3 options...

For example I saw a screenshot with your repo...like this...
![Main_MostrarExprs](https://user-images.githubusercontent.com/45945164/69257734-d34c3c00-0bbb-11ea-9c57-4be762ae1f23.PNG)

How can I output that to my screen...

**Comment by jairopaiva** [comment]
The algorithm has 3 input values: Public Key (X and Y), Position of Private Key to be Discovered (0-31) and Attempt (TRYES) (0-𝟐^𝟔𝟒). Public key values ​​and private key index are "constant" values, the only parameter that changes with each iteration of the algorithm is the TRY value. The algorithm being pseudorandom, will always give the same mathematical expression for the same 3 parameters, the only one that changes and consequently change expression is try value (TRY).

The prameter highlighted in the image below is responsible for displaying the correct mathematical expression for each position of the private key. In GitHub code here this parameter is already set to display the expressions.

![Método](https://user-images.githubusercontent.com/43503826/69260063-041d7880-0b9e-11ea-9ee6-cb68a45dc43c.PNG)

**Comment by jairopaiva** [comment]
I did not make this program to receive input parameters, if you want to change the program, you will have to code it manually.

**Comment by SatoshiNakamotoBitcoins** [comment]
@jairopaiva Thank you for your reply and explanation...

**Comment by jairopaiva** [comment]
You're welcome man, and any question or suggestion, please, contact me.

**Comment by dextronomous** [comment]
Jairopaiva hi there man, hi was wondering how to put another pub in there, in wich file or wich line, could you please help out here, could not figure out the language, or where to put the key thanks again
