### ISSUE TITLE
BitcoinExprCracker Dificuldades

### ISSUE THREAD

**Issue by NightSkyHawk** [jairopaiva/BitcoinExprCracker#3]
Boa Tarde Jairo,

Estou tentando rodar seu programa no Kali Linux,
mas nao consigo faze-lo rodar. Algum comando especifico?
Como e onde devo colocar a chave publica que quero decifrar?
Obrigado.

**Comment by jairopaiva** [comment]
Bom dia amigo, o programa não decifra a chave pública, apenas gera expressões matemáticas que resultem no valor correto da chave privada em determinada posição, tendo como exemplo a chave pública e o correto valor da chave privada para comparação. Tente usar-lo em um Windows com Visual Studio, pois, não lembro se nos downloads que disponibilizei, o fiz com a opção de especificar a chave pública e privada, então seria mais fácil você baixar o código fonte e chumbar diretamente no código os valores.

**Comment by NightSkyHawk** [comment]
Obrigado, já consegui fazê-lo rodar no Kali mesmo após fazer o download do release, aí foi fácil!! Muitíssimo obrigado

**Comment by jairopaiva** [comment]
Disponha amigo!
